# Generated by Django 2.2.28 on 2023-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
    ]
